language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: rgjCHoKm4rn1OzCTIUIDXdQi+Ec0HPHUUllS6lCK+Tx4OM6hs2VBRVIIIM3TA1eTvaQ3f27y7UNxsScSXsLi29VfDJaTxEenHOW6KGR8kUzyD5g4giBExkyn8WqmRnam8Ko/YQ6HKod/jRtWyKQgSG5ivrL+MKWwXNJ0z6dHaRbY7pQGcaaNbtWwEIH+uL7KODov0NdTIVwZlE6KpCup9RbKRrVOTBjmcD6mNgJdEovxSOHaXTlHY3WSUZF1F+sOn/LT32QRHanPSnNQr5YM/QM7OJa4C3a/H7PrrdxXGbptgN910aquzNO0tv6Fg4BtFkwn8QOm3c8zCA1/D6a/kXiiVEhFQWcyflPFNv/YJ4RUIQdhhLU9tEpiIFBn18efeZ/i7uL/22pTG7x36ADDogiBM11Xde1Cza86DrfxPNdLvuw55b6Qzap7MVVpv9OEtYHou08nlMLZB02mWU7baJpDluhm01yVhFgjD4lqS5MfSrx2t1s0ZO8ZQSPvUrzj/ejohmqwAywCgLy6LGzoeORZoFDSG738xx9wFyTzZ5bJnx3MgVdVPh9EGD5ub6xg+6WIbQaWchJSmiPERD8Qqn0kMLN8qNGAGEglC15A6TPHlRmiwnqwwtpRYnJA/Lx0rhSfdorkDruuAgdkvygOnhuH8MDZkOK0zRZ5CU7aKWU=
  on:
    tags: true
  skip_existing: true
